namespace: samdoran
name: macos
version: 2.5.2
readme: README.md
authors:
  - Sam Doran <sdoran@redhat.com>

description: Roles and custom content for manangig macOS

license:
  - GPL-2.0-or-later

tags:
  - development
  - system
  - macos
  - xcode
  - python

dependencies: {}

repository: http://github.com/samdoran/ansible-collection-macos
documentation: http://github.com/samdoran/ansible-collection-macos/README.md
homepage: http://github.com/samdoran/ansible-collection-macos
issues: http://github.com/samdoran/ansible-collection-macos/issues

build_ignore: []
