- name: Ensure Python version is valid
  assert:
    msg: "Invalid Python version given: {{ macos_python_version }}. Must be x.y.z and a valid Python version.."
    that:
      - macos_python_version is match('[23]\.[0-9]{1,2}\.[0-9]+')
  tags:
    - macos_python

- name: Create temp path
  file:
    path: "{{ macos_python_tmp_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  tags:
    - macos_python

- name: Download Python installer
  get_url:
    url: "{{ _macos_python_pkg_url }}"
    dest: "{{ macos_python_tmp_path }}"
    mode: '0644'
  register: download
  notify: cleanup temp files
  tags:
    - macos_python

- name: Install Python
  command: installer -pkg {{ download.dest }} -target /
  args:
    creates: /Library/Frameworks/Python.framework/Versions/{{ macos_python_major_minor_version }}
  tags:
    - macos_python

- name: Install system CA certificates for Python
  samdoran.macos.bootstrap_certs:
  vars:
    ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/{{ macos_python_major_minor_version }}/bin/python3
  tags:
    - macos_python
    - macos_python_certs

- name: Download and extract libyaml source
  unarchive:
    src: https://pyyaml.org/download/libyaml/yaml-{{ macos_python_libyaml_version }}.zip
    dest: "{{ macos_python_tmp_path }}"
    creates: "{{ macos_python_tmp_path }}/yaml-{{ macos_python_libyaml_version }}"
    remote_src: yes
  become: no
  notify: cleanup temp files
  when: macos_python_compile_libyaml | bool
  tags:
    - macos_python

- name: Compile libyaml
  shell: >
    ./configure --enable-shared=no --with-pic --prefix={{ _macos_python_build_path }} --disable-dependency-tracking &&
    make &&
    make install
  become: no
  when: macos_python_compile_libyaml | bool
  args:
    chdir: "{{ macos_python_tmp_path }}/yaml-{{ macos_python_libyaml_version }}"
  tags:
    - macos_python

- name: Install Python packages
  pip:
    executable: /Library/Frameworks/Python.framework/Versions/{{ macos_python_major_minor_version }}/bin/pip3
    extra_args: "{{ macos_python_pip_extra_args }}"
    name: "{{ macos_python_packages }}"
  become: no
  environment:
    C_INCLUDE_PATH: "{{ _macos_python_build_path }}/include"
    LIBRARY_PATH: "{{ _macos_python_build_path }}/lib"
  tags:
    - macos_python
